from typing import Any

from backend.app.agent.reasoning.llm_planner import generate_llm_plan


class RemediationPlan:
    def __init__(
        self,
        action: str,
        target: str,
        rationale: str,
        expected_state: dict[str, str],
        risk: str,
        requires_authorization: bool,
        confidence: float,
    ):
        self.action = action
        self.target = target
        self.rationale = rationale
        self.expected_state = expected_state
        self.risk = risk
        self.requires_authorization = requires_authorization
        self.confidence = confidence


def plan_to_dict(plan: RemediationPlan) -> dict[str, Any]:
    return {
        "action": plan.action,
        "target": plan.target,
        "rationale": plan.rationale,
        "expected_state": plan.expected_state,
        "risk": plan.risk,
        "requires_authorization": plan.requires_authorization,
        "confidence": plan.confidence,
    }


def _expected_state_for_action(
    action: str | None,
    it_state: dict[str, str],
) -> dict[str, str]:

    if action == "restart_vpn_client":
        return {
            "vpn_client": "connected",
            "network": "connected",
            "vpn_gateway": "operational",
            "authentication": "valid",
        }

    if action == "reset_password":
        return {
            "authentication": "valid",
        }

    if action == "install_software":
        return {
            "endpoint": "operational",
            "software_installation": "installed",
        }

    if action == "request_application_access":
        return {
            "authentication": "valid",
            "access_request": "provisioned",
        }

    if action == "grant_admin_access":
        return {
            "authentication": "valid",
            "access_request": "provisioned",
        }

    if action == "escalate_vpn_troubleshooting":
        return {
            "vpn_client": it_state.get(
                "vpn_client",
                "unknown",
            ),
        }

    return {}


def _plan_from_llm(
    llm_plan: dict[str, Any],
    it_state: dict[str, str],
) -> RemediationPlan | None:

    action = llm_plan.get("action")

    if not action:
        return None

    expected_state = _expected_state_for_action(
        action,
        it_state,
    )

    if not expected_state:
        return None

    return RemediationPlan(
        action=action,
        target=llm_plan.get(
            "target",
            "IT Environment",
        ),
        rationale=llm_plan.get(
            "rationale",
            "Candidate remediation generated by the reasoning layer.",
        ),
        expected_state=expected_state,
        risk=llm_plan.get(
            "risk",
            "Medium",
        ),
        requires_authorization=llm_plan.get(
            "requires_authorization",
            True,
        ),
        confidence=llm_plan.get(
            "confidence",
            0.80,
        ),
    )


def generate_plan(
    intent: str,
    category: str,
    it_state: dict[str, str],
    knowledge_sources: list[Any],
) -> RemediationPlan | None:
    """
    Generate a candidate remediation plan.

    PHOENIX first attempts LLM-based reasoning.

    If the LLM is unavailable, returns an invalid candidate,
    or produces an unsupported action, the deterministic
    planner remains the safe fallback.

    The planner only proposes an action.

    Policy decides whether the action is allowed.
    Tool Gateway performs controlled execution.
    Verification confirms the resulting IT state.
    """

    # =========================================================
    # 1. LLM REASONING
    # =========================================================

    llm_plan = generate_llm_plan(
        intent=intent,
        category=category,
        it_state=it_state,
        knowledge_sources=knowledge_sources,
    )

    if llm_plan is not None:
        candidate = _plan_from_llm(
            llm_plan,
            it_state=it_state,
        )

        if candidate is not None:
            return candidate

    # =========================================================
    # 2. DETERMINISTIC FALLBACK
    # =========================================================

    action: str | None = None
    target = "IT Environment"

    rationale = (
        "No validated LLM plan was available, so the deterministic "
        "PHOENIX remediation rules were used."
    )

    risk = "Medium"
    requires_authorization = True
    confidence = 0.80

    # =========================================================
    # VPN TROUBLESHOOTING
    # =========================================================

    if intent == "troubleshoot_vpn":

        target = "VPN Client"

        if (
            it_state.get("vpn_client") == "disconnected"
            and it_state.get("network") == "connected"
            and it_state.get("vpn_gateway") == "operational"
            and it_state.get("authentication") == "valid"
        ):
            action = "restart_vpn_client"

            rationale = (
                "The endpoint network is connected, the VPN gateway "
                "is operational, authentication is valid, and the VPN "
                "client is disconnected. A controlled VPN client restart "
                "is therefore the most appropriate candidate remediation."
            )

            risk = "Low"
            requires_authorization = True
            confidence = 0.94

        else:
            action = "escalate_vpn_troubleshooting"

            rationale = (
                "The observed VPN environment does not satisfy the "
                "conditions for a safe automated VPN client restart. "
                "The request should be escalated for human troubleshooting."
            )

            risk = "Low"
            requires_authorization = True
            confidence = 0.90

    # =========================================================
    # PASSWORD RESET
    # =========================================================

    elif intent == "reset_password":

        action = "reset_password"
        target = "User Account"

        rationale = (
            "The request is a standard password-reset operation "
            "supported by the controlled helpdesk workflow."
        )

        risk = "Medium"
        requires_authorization = True
        confidence = 0.92

    # =========================================================
    # SOFTWARE INSTALLATION
    # =========================================================

    elif intent == "install_software":

        action = "install_software"

        target = it_state.get(
            "requested_software",
            "Requested Software",
        )

        rationale = (
            "The request identifies software installation as the "
            "required remediation. Installation must proceed through "
            "the controlled tool gateway and applicable policy."
        )

        risk = "Medium"
        requires_authorization = True
        confidence = 0.90

    # =========================================================
    # PRIVILEGED ACCESS
    # =========================================================

    elif intent == "request_privileged_access":

        action = "grant_admin_access"

        target = it_state.get(
            "requested_resource",
            "Privileged Resource",
        )

        rationale = (
            "The request requires privileged administrative access. "
            "The action is proposed for policy evaluation but must "
            "not bypass authorization controls."
        )

        risk = "High"
        requires_authorization = True
        confidence = 0.95

    # =========================================================
    # STANDARD APPLICATION ACCESS
    #
    # The understanding layer uses request_access.
    # request_application_access is also accepted for compatibility
    # with the LLM planner and existing workflow.
    # =========================================================

    elif intent in {
        "request_access",
        "request_application_access",
    }:

        action = "request_application_access"

        target = it_state.get(
            "requested_resource",
            "Requested Application",
        )

        rationale = (
            "The request requires standard application access. "
            "The access request must be evaluated by the policy engine "
            "before controlled execution."
        )

        risk = "Medium"
        requires_authorization = True
        confidence = 0.90

    # =========================================================
    # UNKNOWN REQUEST
    # =========================================================

    else:
        return None

    return RemediationPlan(
        action=action,
        target=target,
        rationale=rationale,
        expected_state=_expected_state_for_action(
            action,
            it_state,
        ),
        risk=risk,
        requires_authorization=requires_authorization,
        confidence=confidence,
    )